---
title: "p8105_hw1_LG2982"
author: "Lizbeth Gomez"
date: "9/15/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # this is how I load a library

```


```{r, Problem_1}


problem_1_df = tibble(
  x = rnorm(8, sd = .5), #Created a random sample with 8 observations
  vec_logical = (x> 0),  # Cretes a logical vector that makes all x obs >0
  vec_char = c("Coding", "in", "R", "language", "is", "so", "much","fun"), #created a vector with a character
  vec_factor = factor(c("male", "male", "female", "female","male", "male", "female", "female")) # created a variable with two level factor
)

problem_1_df%>%
  summarise(meanx = mean(x))  # the mean of x (a random sample of size 8 from a standard Normal distribution is 0.0563209	)

problem_1_df%>%
  summarise(meanlog = mean(vec_logical)) # mean of this is 0.375	

problem_1_df%>%
  summarise(meanchar = mean(vec_char)) # cant do this because is a character vector

problem_1_df%>%
  summarise(meanfact = mean(vec_factor)) #cant do this because is a factor vector



```


```{r, eval=FALSE}
problem_1_df%>% ###NEED HELP HERE
  mutate  (as.numeric(vec_logical))

problem_1_df%>%
  mutate (as.numeric(vec_factor))

problem_1_df%>%
  mutate (as.numeric(vec_char))
```


```{r, Problem_2}

problem_2_df = tibble(
   x = rnorm(500, sd = .5),
   y = rnorm(500, sd = .5),
   vec_logic = (x + y > 1),
   vec_char =( as.numeric(vec_logic)),
   vec_fact =( as.factor(vec_logic ))
)
    nrow(problem_2_df)   
    ncol(problem_2_df)  # *the size of the dataset 500 by 5
    
    
   problem_2_df%>%
    summarise(mean_x = mean(x), 
              sd(x), 
              median (x))  # mean = 0.00460194, stdev =0.5161848 and median =-0.006032529	
  
  problem_2_df%>%
    count(x +y >1) %>%
    mutate(freq = n / sum(n)) #The proportion of cases for which x + y > 1 = 7.6%
    
  
  
ggplot(problem_2_df, aes(x = x, y = y, color = x + y > 1)) + geom_point() # colored scatterplot where blue are x + y > 1 and pink are the values x + y =< 1

ggplot(problem_2_df, aes(x = x, y = y, color = vec_char)) + geom_point() # colored scatterplot where darker blue are the vaues are closer to zero and lighter blue are those closer to 1

ggplot(problem_2_df, aes(x = x, y = y, color = vec_fact)) + geom_point()# colored scatterplot where blue are x + y > 1 and pink are the values x + y =< 1



```

